
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-int-svc
  labels:
    app: api-gateway
    group: api
    facing: internal
    impl: internal
    ms: {{ .Values.ms | quote }}
spec:
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 8080
    name: tcp
  - protocol: TCP
    port: {{ .Values.api_gateway.metrics.port }}
    targetPort: {{ .Values.api_gateway.metrics.port }}
    name: metrics
  type: ClusterIP
  selector:
    app: api-gateway
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: api-gateway
    ms: {{ .Values.ms | quote }}
  name: api-gateway
spec:
  endpoints:
  - honorLabels: true
    port: metrics
    path: "{{ .Values.api_gateway.metrics.basePath }}{{ .Values.api_gateway.metrics.prometheus.path }}"
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}  
  selector:
    matchLabels:
      app: api-gateway