
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    app: {{ include "api-gateway.fullname" . }}
    group: api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api-registry.fullname" . }}
  labels:
    app: {{ include "api-registry.fullname" . }}
    group: api
