apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deviceinfoquery.fullname" . }}-credentials
  labels: {{- include "deviceinfoquery.labels" . | nindent 4 }}
data:
  postgres_username: {{ .Values.postgresql.userName | b64enc }}
  postgres_password: {{ .Values.postgresql.password | b64enc }}
  client_id: {{ .Values.deviceinfoquery_api.client_id | b64enc }}
  client_secret: {{ .Values.deviceinfoquery_api.client_secret | b64enc }}
  swm_password: {{ .Values.deviceinfoquery_api.swm_password | b64enc }}