apiVersion: v1
kind: Service
metadata:
  name: oss-ro-api-int-svc
  labels:
    app: ro-api
    group: api
    ms: {{ .Values.ms | quote }}
    facing: internal
    impl: native
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: web
  selector:
    app: ro-api