apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ro-api.fullname" . }}
  labels:
    app: ro-api
    group: api
    ms: {{ .Values.ms | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ro-sp.fullname" . }}
  labels:
    app: ro-sp
    group: api
    ms: {{ .Values.ms | quote }}