apiVersion: v1
kind: Secret
metadata:
    name: association-credentials
data:
    postgres_username: {{ .Values.postgresql.userName | b64enc }}
    postgres_password: {{ .Values.postgresql.password | b64enc }}
    client_id: {{ .Values.association_api.client_id | b64enc }}
    client_secret: {{ .Values.association_api.client_secret | b64enc }}
    service_notification_kafka_client_key_password: {{ .Values.association_api.service_notification_kafka_client_key_password | b64enc }}
    service_notification_kafka_client_keystore_password: {{ .Values.association_api.service_notification_kafka_client_keystore_password | b64enc }}
    service_notification_kafka_client_truststore_password: {{ .Values.association_api.service_notification_kafka_client_truststore_password | b64enc }}
    service_user_auth_password: {{ .Values.association_api.service_user_auth_password | b64enc }}
    swm_password: {{ .Values.association_api.swm_password | b64enc }}