apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uidam-authorization-server.fullname" . }}-credentials
  labels: {{- include "uidam-authorization-server.labels" . | nindent 4 }}
data:
  username: {{ .Values.postgres.userName | b64enc | quote }}
  password: {{ .Values.postgres.password | b64enc | quote }}
  keystorePassword: {{ .Values.secrets.keystorePassword | b64enc | quote }}
  ignite.recaptcha.key.secret: {{ .Values.secrets.igniteRecaptchaKeySecret | b64enc | quote }}
  clientsecretkey: {{ .Values.secrets.clientsecretkey | b64enc | quote }}
  clientsecretsalt: {{ .Values.secrets.clientsecretsalt | b64enc | quote }}
  clientSecret: {{ .Values.secrets.clientSecret | b64enc | quote }}

