apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uidam-authorization-server.fullname" . }}-jks
  labels: {{- include "uidam-authorization-server.labels" . | nindent 4 }}
data:
  jks-file: |-
    {{ .Values.jks_file }}