{{- if .Values.notification.config.createDefault }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uidam-user-management.fullname" . }}-notification-config
  labels: {{- include "uidam-user-management.labels" . | nindent 4 }}
data:
  uidam-user-management-notification-config.json: |
    [
      {
        "notificationId": "UIDAM_USER_VERIFY_ACCOUNT",
        "enabled": true,
        "email": {
            "enabled": true,
            "templates": [
                {
                    "locale": "en_US",
                    "default": "true",
                    "brand": "default",
                    "from": "{{ .Values.notification.email.overrideSender | default "admin@eclipse-ecsp.com" }}",
                    "subject": "UIDAM Email Verification",
                    "reference-html": "htmls/thymeleaf-template.html",
                    "images": {
                        "Image-hdr_brand": "images/harman.png",
                        "Image-hdr_picture": "images/header_pic.png"
                    },
                    "body": {
                        "salutation": "Greetings [[${name}]]!",
                        "body": "Please verify your UIDAM account that is associated with this email address.<br/><a th:href=\"${emailLink}\">Verify My Email</a><br/>If clicking the button doesn't seem to work, you can copy and paste the following link into your browser.<br/>[[${emailLink}]]",
                        "footer": "Thanks",
                        "sender": "{{ .Values.notification.email.overrideSender | default "admin@eclipse-ecsp.com" }}"
                    }
                }
            ]
        }
      },
      {
        "notificationId": "UIDAM_USER_PASSWORD_RECOVERY",
        "enabled": true,
        "email": {
            "enabled": true,
            "templates": [
                {
                    "locale": "en_US",
                    "default": "true",
                    "from": "{{ .Values.notification.email.overrideSender | default "admin@eclipse-ecsp.com" }}",
                    "subject": "UIDAM notification",
                    "reference-html": "htmls/thymeleaf-template.html",
                    "images": {
                        "Image-hdr_brand": "images/harman.png",
                        "Image-hdr_picture": "images/header_pic.png"
                    },
                    "body": {
                        "salutation": "Greetings [[${name}]]!",
                        "body": "We received a request to reset the password for the [[${email}]] account that is associated with this email address. If you made this request, please click the button below to securely reset your password. <br/><a th:href=\"${changePasswordUrl}\">Reset Password</a><br /> If clicking the button doesn't seem to work, you can copy and paste the following link into your browser.<br/>[[${changePasswordUrl}]]<br/> If you did not request to have your password reset, disregard this email and no changes to your account will be made.",
                        "footer": "Thanks",
                        "sender": "{{ .Values.notification.email.overrideSender | default "admin@eclipse-ecsp.com" }}"
                    }
                }
            ]
          }
      }
    ]
{{- end }}