apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uidam-user-management.fullname" . }}-credentials
  labels: {{- include "uidam-user-management.labels" . | nindent 4 }}
data:
  username: {{ .Values.postgres.userName | b64enc | quote }}
  password: {{ .Values.postgres.password | b64enc | quote }}
  clientsecretkey: {{ .Values.clientsecretkey | b64enc | quote }}
  clientsecretsalt: {{ .Values.clientsecretsalt | b64enc | quote }}
  revokeTokenClientSecret: {{ .Values.revokeTokenClientSecret | b64enc | quote }}
  smtp_username: {{ .Values.notification.email.username | b64enc | quote }}
  smtp_passwd: {{ .Values.notification.email.passwd | b64enc | quote }}
  liquibase_clientsecret: {{ .Values.postgres.liquibase.clientsecret | b64enc | quote }}
  liquibase_userpwd: {{ .Values.postgres.liquibase.userpwd | b64enc | quote }}
  liquibase_usersalt: {{ .Values.postgres.liquibase.usersalt | b64enc | quote }}