apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels: {{- include "postgresql.labels" . | nindent 4 }}
data:
  username: TO-BE-UPDATED
  password: TO-BE-UPDATED
