apiVersion: v1
kind: Secret
metadata:
    name: device-auth-credentials
data:
    postgres_username: {{ .Values.postgresql.userName | b64enc }}
    postgres_password: {{ .Values.postgresql.password | b64enc }}
    client_id: {{ .Values.device_auth_api.client_id | b64enc }}
    client_secret: {{ .Values.device_auth_api.client_secret | b64enc }}
    hcp_auth_qualifier_secret_key: {{ .Values.device_auth_api.hcp_auth_qualifier_secret_key | b64enc }}
    hcp_activation_preSharedKey: {{ .Values.device_auth_api.hcp_activation_preSharedKey | b64enc }}