replicaCount: 2

image:
  repository: docker.io/eclipseecsp/uidam-authorization-server
  pullPolicy: IfNotPresent
  tag: 1.0.0

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

tenant:
  tenantId: "tenant-001"
  tenantName: "example-tenant"
  jksEnabled: "true"
  alias: "uidamauthserver"
  cache:
    expiration: "60"
    maxsize: "100"
    clientids: "token-mgmt,device-mgmt"
  account:
    accountId: "acc-001"
    accountName: "example-account"
    accountType: "B2B"
    accountFieldEnabled: "true"
  client:
    accessTokenTtl: "3600"
    idTokenTtl: "3600"
    refreshTokenTtl: "86400"
    authCodeTtl: "300"
    oauthScopeCustomization: "false"
  user:
    captchaAfterInvalidFailures: "1"
    captchaRequired: "false"
    maxAllowedLoginAttempts: "5"
    jwtAdditionalClaimAttributes: "accountType, accountName"
  externalUrls:
    userManagementUrl: "http://uidam-user-management:8080"
    clientByClientIdEndpoint: "/v1/oauth2/client/{clientId}"
    userByUsernameEndpoint: "/v1/users/{userName}/byUserName"
    recoveryNotificationEndpoint: "/v1/users/{userName}/recovery/forgotpassword"
    updatePasswordUsingSecretEndpoint: "/v1/users/recovery/set-password"
  keyStore:
    keyStoreFilename: "uidamauthserver.jks"
    keyAlias: "uidamauthserver"
    keyType: "JKS"
  cert:
    jwtPublicKey: "app.pub"
    jwtPrivateKey: "app.key"
    jwtKeyId: "jwt-key-001"
  captcha:
    recaptchaVerifyUrl: "https://www.google.com/recaptcha/api/siteverify"
    recaptchaKeySite: "recaptcha-site-key"
  externalIdpEnabled: true
  internalLoginEnabled: true
  externalIdpClientName: federated-user-client
  externalIdpRegisteredClients:
    - clientName: Google
      registrationId: google
      clientId: google-client-id
      clientSecret: google-client-secret
      clientAuthenticationMethod: client_secret_basic
      scope: openid, profile, email, address, phone
      authorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      tokenUri: https://www.googleapis.com/oauth2/v4/token
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      userNameAttributeName: sub
      jwkSetUri: https://www.googleapis.com/oauth2/v3/certs
      tokenInfoSource: FETCH_INTERNAL_USER
      createUserMode: CREATE_INTERNAL_USER
      defaultUserRoles: VEHICLE_OWNER
      claimMappings: firstName#given_name,lastName#family_name,email#email
    - clientName: Github
      registrationId: github
      clientId: github-client-id
      clientSecret: github-client-secret
      clientAuthenticationMethod: client_secret_basic
      scope: read:user
      authorizationUri: https://github.com/login/oauth/authorize
      tokenUri: https://github.com/login/oauth/access_token
      userInfoUri: https://api.github.com/user
      userNameAttributeName: id
      jwkSetUri: https://www.googleapis.com/oauth2/v3/certs
      tokenInfoSource: FETCH_INTERNAL_USER
      createUserMode: CREATE_INTERNAL_USER
      defaultUserRoles: VEHICLE_OWNER
      claimMappings: firstName#name,email#email
    - clientName: Cognito
      registrationId: cognito
      clientId: cognito-client-id
      clientSecret: cognito-client-secret
      clientAuthenticationMethod: client_secret_basic
      scope: openid,profile
      authorizationUri: https://your-cognito-domain/oauth2/authorize
      tokenUri: https://your-cognito-domain/oauth2/token
      userInfoUri: https://your-cognito-domain/oauth2/userinfo
      userNameAttributeName: sub
      jwkSetUri: https://your-cognito-domain/.well-known/jwks.json
      tokenInfoSource: FETCH_INTERNAL_USER
      createUserMode: CREATE_INTERNAL_USER
      defaultUserRoles: VEHICLE_OWNER
      claimMappings: firstName#given_name,lastName#family_name,email#email
    - clientName: Azure
      registrationId: azureidp
      clientId: azure-client-id
      clientSecret: azure-client-secret
      clientAuthenticationMethod: client_secret_post
      scope: openid
      authorizationUri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
      tokenUri: https://login.microsoftonline.com/common/oauth2/v2.0/token
      userInfoUri: https://graph.microsoft.com/oidc/userinfo
      userNameAttributeName: sub
      jwkSetUri: https://login.microsoftonline.com/common/discovery/v2.0/keys
      tokenInfoSource: FETCH_INTERNAL_USER
      createUserMode: CREATE_INTERNAL_USER
      defaultUserRoles: VEHICLE_OWNER
      claimMappings: firstName#given_name,lastName#family_name,email#email

service:
  type: ClusterIP
  port: 9443

ingress:
  enabled: true
  className: alb
  groupName: external
  scheme: internet-facing
  targetType: ip
  inboundCidrs: ["0.0.0.0/0"]
  tls:
    enabled: true
    sslRedirect: false
  additionalAnnotations: {}
  hosts:
    - hostPrefix: auth-server
      paths:
        - /

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

distributedTracing:
  enabled: false

environmentDomainName: ecsp.example.com

uiTemplatePath: "file:///tmp/customui/templates/"
uiStaticPath: "file:///tmp/customui/static"
javaOpts: -Xms128m -Xmx512m -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxMetaspaceSize=256m

logging:
  GRAYLOG_ENABLED: "false"
  GRAYLOG_HOST: graylog3-tcp.graylog.svc.cluster.local
  GRAYLOG_PORT: "12201"
  NEVER_BLOCK_FOR_GRAYLOG: "false"
  LOG_FOLDER: logs/
  LOG_LEVEL: ERROR
  IGNITE_LOG_LEVEL: ERROR
  SVC_LOG_LEVEL: INFO
  STORAGE_LOG_LEVEL: ERROR
  SPRING_LOG_LEVEL: ERROR
  LOG_APPENDER: "STDOUT"

postgres:
  host: postgresql
  port: 5432
  secretName: uidam-authorization-server-credentials
  userName: uidamuser
  password: uidampass
  databaseName: postgresql
  schemaName: eclipseecsp
  max_idle_time: "0"
  data_source_properties:
    cachePrepStmts: "true"
    prepStmtCacheSize: "250"
    prepStmtCacheSqlLimit: "2048"
  connecion_timeout_ms: "60000"
  expected99thPercentileMs: "60000"
  max_pool_size: "30"

server_servlet_session_timeout: "5m"
user_session_force_login: "true"

health:
  postgresdb:
    monitor:
      enabled: "true"
      restart_on_failure: "true"

metrics:
  prometheus:
    enabled: "true"
    agent:
      port: "9100"
      port_exposed: "9100"
  postgresdb:
    enabled: "true"
    executor_shutdown_buffer_ms: "2000"
    thread:
      freq_ms: "5000"
      intial_delay_ms: "2000"

jks_file: uidamauthserver.jks

nfsServerUrl: nfs.example.com:/shared
sharedStoragePvcName: uidam-shared-storage

app_key: |
  -----BEGIN PRIVATE KEY-----
  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCx2Vc/g6RkznSk
  bqzE92MkwZB/yrFn2tZtVf0NieAzGN7HeELoqcqxMHPXv7Ua6vYSQNPSa73SBG82
  QWYlZ4k+7GopN2LuVNu0fUMIP3TWYyvpw5OPZYJm9IW/zEfu/XtxUCMEL/PNrvXI
  vNJfnfYhgtjCM24RrlAZvddwRnw6sOADE+NzxgZVPJu0UiRDU85UiEeD7J+WgUHA
  idTqmLu3Pn7eWVY9SBLPUTm+soeNfGXFeRGBMBpWJjEwZaAtF640ES5kcmTcquxq
  M5F/31vVooswEmpn9x6js/4UGmByAMYkH2Za5F4nFBKK4C+FCqkavDmi2PT+Oh8P
  tjJ+BK3HAgMBAAECggEAAPf9MQlW5GQ0sMYPjS6y12Fx2/HvDpL934n8IU4/g+BE
  ouijSKjxKiAbvJ94ZOVwqtC36diqDh8X3KXCNiyLkEOLMWut1/hrWyM37XwSu3p5
  8JbrwXhuCoDJU3Jq1gUtxNmI7Sicxdjurw5TK6/TEyW4Ral0hMq8TbCoQi8QolxD
  FRDOdL9hQARBcY0ETMgft/+yDEhM9a3XcpSz7fsUVLMe63uF3wVNpNmfR1ylndVx
  UMltThkrkno3tFeCxuaT0p0tw6o+B9Q0Fs7l4eCL12LcfKI9GsrgEOywJX0BR+rz
  y5c8bja+BFQQmGqLJUJjUAUsjm9QM25GmvKGumc0lQKBgQDbfycz5yjR+Sw8JCJd
  zjVJwmz6+KeNIMDqLawXWvYdwsmN+qmB3atxUpzJWPv7CNp+PC34bUitTPZJOM76
  5+y6WA+9BDif2nSQ6k3jXrj1C0enW+ZEZA0uZgIU0Tfom6H6iT2JDNyUmyFqeEjn
  rF9xRrVdaZDre1dVJwxiLtww8wKBgQDPbRRODJ/JuKsXiE1t0X7Uzc+5qbCprKkW
  UgwPo50J7One7y2s7DE5/Mn09nCwjpUUbtLiiDI/CDz+xx8tneN1n2GUuVz2COe+
  k/Z+Brz9laqPqZRAbpfIRZGWnUHGqP+Yg0P0sjBCsewdB7XJgXZ6x9hDFMavTz5e
  CERm3dLk3QKBgG1dZ50W2mH0szOsFWuD6U09EKvj5SgOX9DOvOZOLj8Z5O9XK8pH
  NrsaHIC+U577BFLNjWIwoXun0zcclRSzJmKaqgzV45jSci4acICPm7yMyED9Kzh8
  WYz6yqKwtBi0IvsAEqcMv4NT4Ex6bmjwnAWG46sNhGWwaQ1GjYcGLjQ9AoGBAMxL
  vwfwXyCrBbgzwy86exTVcJaIjztOl2sofECbAPzZnq64G+CI8SMP20mtv+flRufN
  D1+WjQaP8qNtM0QWkgUzaUS2HN0mgDmwOcJ+mH2af1bnyuB7DHtwKaiSUkp8AOIR
  x0imh+nom4ksItvI6wya8GGBgP8BqYer1NML/77xAoGAELNMsP/FD6wuUzgSf39b
  APMtHweXSuOELJH7AZ6CkNLXLUSFjYS4oi85wTQjY3lma/FpDoynvts3VUDQK79I
  ndq6ibIZXI/0vu+1qH9cmfnbZuAhhKQJnCWoPSXpBzqVpU9wXu0TYaTXOKjFYQRX
  xc3LnsWT3KrJGTrrqxlsOPg=
  -----END PRIVATE KEY-----

app_pub: |
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsdlXP4OkZM50pG6sxPdj
  JMGQf8qxZ9rWbVX9DYngMxjex3hC6KnKsTBz17+1Gur2EkDT0mu90gRvNkFmJWeJ
  PuxqKTdi7lTbtH1DCD901mMr6cOTj2WCZvSFv8xH7v17cVAjBC/zza71yLzSX532
  IYLYwjNuEa5QGb3XcEZ8OrDgAxPjc8YGVTybtFIkQ1POVIhHg+yfloFBwInU6pi7
  tz5+3llWPUgSz1E5vrKHjXxlxXkRgTAaViYxMGWgLReuNBEuZHJk3KrsajORf99b
  1aKLMBJqZ/ceo7P+FBpgcgDGJB9mWuReJxQSiuAvhQqpGrw5otj0/jofD7YyfgSt
  xwIDAQAB
  -----END PUBLIC KEY-----

uidam_pub: |
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsdlXP4OkZM50pG6sxPdj
  JMGQf8qxZ9rWbVX9DYngMxjex3hC6KnKsTBz17+1Gur2EkDT0mu90gRvNkFmJWeJ
  PuxqKTdi7lTbtH1DCD901mMr6cOTj2WCZvSFv8xH7v17cVAjBC/zza71yLzSX532
  IYLYwjNuEa5QGb3XcEZ8OrDgAxPjc8YGVTybtFIkQ1POVIhHg+yfloFBwInU6pi7
  tz5+3llWPUgSz1E5vrKHjXxlxXkRgTAaViYxMGWgLReuNBEuZHJk3KrsajORf99b
  1aKLMBJqZ/ceo7P+FBpgcgDGJB9mWuReJxQSiuAvhQqpGrw5otj0/jofD7YyfgSt
  xwIDAQAB
  -----END PUBLIC KEY-----

secrets:
  keystorePassword: "changeit"
  igniteRecaptchaKeySecret: "0892ea5b960efb28187bac63ef3cfd0aeba977e71271b672f0efdae738537e36"
  clientsecretkey: "bo18x5L72WG/GMJr8kMelM3uQzs38HZLRTKMO8zPlVE="
  clientsecretsalt: "6efdc686848a38b853c80de00dd95e9b"
  clientSecret: "9FD5s6Rvl4y1SMbdd9yaHPMeL6/Xi5DC2BfUiYDCduQ="
